### ISSUE TITLE
[FEATURE] adding hi localization to the project.

### ISSUE THREAD

**Issue by nikhil12377** [mikhael28/paretOS#112]
Adding hindi language support to UI/UX.

**Comment by mikhael28** [comment]
Almost done @nikhil12377 , take a quick look at the comment I left in the PR!

**Comment by nikhil12377** [comment]
@mikhael28 Should i close this issue?

**Comment by mikhael28** [comment]
Yes, please do!

-
Michael 'Misha' Litchev


On September 15, 2021, Steve Denton ***@***.***> wrote:
> @mikhael28 <https://github.com/mikhael28> Should i close this issue?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mikhael28/paretOS/issues/112#issuecomment-
920750141>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ADUAHC22DP24UGXPNQ7BORTUCG35RANCNFSM5D3GNJ6A>.
