### ISSUE TITLE
Replace uuid library with nanoid library + shallow render tests

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#162]
NanoId has a few advantages over uuid - the strings themselves are smaller, which means their performance is better & the bundle size for the npm package is better. Please refer to the following blog post for details: https://blog.bitsrc.io/why-is-nanoid-replacing-uuid-1b5100e62ed2

Let's replace every instance of uuid generation in our application with NanoId. Additionally, please create a simple `ShallowRender` test for that particular component and include with your pull-request.

**Comment by AleksandrKurilov** [comment]
I could to do it, can you assign me to this one? I've never made ShallowRender tests, but I think I will be able to figure out it.

**Comment by mikhael28** [comment]
Sounds good @AleksandrKurilov I’m assigning you! @jayeclark any testing advice for him on using Puppeteer/Enzyme?

**Comment by mikhael28** [comment]
@AleksandrKurilov I see your other PR’s, I will be reviewing them later tonight! Thanks for your patience.

**Comment by jayeclark** [comment]
Shoot, @AleksandrKurilov, I'm so sorry - I didn't realize you were working on this/someone was assigned to this.... I just refactored the user onboarding form and in the process replaced all the uuid's with nanoid (there were only 7 of them in the whole repo, and most of them were in that component so I figured I'd just knock them all out as part of that PR.)

My bad. 😬  

I didn't make any tests though so I'm going to keep this issue open!

As far as testing, @mikhael28 I'm not sure shallow rendering is the best strategy here. Looking at the code, nanoid isn't actually called until the form in each relevant component is submitted. Since those forms use various imported components from node_modules, testing them would require rendering child components, not just the main component, right? React does have a built in [shallow renderer]( https://reactjs.org/docs/shallow-renderer.html#:~:text=When%20writing%20unit%20tests%20for,does%20not%20require%20a%20DOM.) but it might be better to just use the same general strategy as is used in Board.spec.tsx. Let me know if I'm missing the point of the test request, though!

**Comment by AleksandrKurilov** [comment]
> 

@jayeclark Everything is fine, I'm back to modal windows for now, after I'm done with modal windows, I'll deal with the tests. Thank you.

**Comment by mikhael28** [comment]
@AleksandrKurilov @jayeclark I'm going to go ahead and close this issue, because I don't think the test's are critical/the issue does a poor job of explaining what to do. However, now that Jaye has replaced the uuid's with the nanoid library - since that was the primary item in the ticket, I'm going to go ahead and close it.
