### ISSUE TITLE
I18n Language Change Props Not Propagating

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#31]
Our vision is to support multiple languages with the ParetOS. To do so, we have added the Amplify I18N library to help us with replacing certain UI/UX language based on the device's detected language. Right now, we support Spanish and Luganda. 

However, there is a problem. In `App.js` there is a language bar, in the side-nav, where someone can change the active language of the application. When they change the language, they can see the language changing in the side-nav - but not in the other components, until they migrate to another container (using the `history` object). Then, the language propagates. My theory is that these language props are not being propagated correctly somehow, perhaps the event needs to be triggered outside the side-nav? Maybe do some research on Google.

**Comment by jayeclark** [comment]
Assigning this to myself - I found the issue. The state that leftNav is updating is only relevant to LeftNav -- the rest of the app uses I18N, but changes to the language button in LeftNav never actually update the I18N language setting.

**Comment by jayeclark** [comment]
Welp, in addition: [https://github.com/aws-amplify/amplify-ui/issues/256](https://github.com/aws-amplify/amplify-ui/issues/256)

Even after you update the language, some fancy footwork is needed to get the changes to propagate. A call to AWS Amplify's I18N.setLanguage() doesn't trigger a re-render.

**Comment by jayeclark** [comment]
![langtoggle](https://user-images.githubusercontent.com/84106309/161350972-efeb8801-78f6-4196-9af4-79019105d931.gif)

Will take me a week or so to fully implement throughout the codebase, but - in theory the problem of re-rendering all relevant mounted components when a new language is selected has been solved! 

It requires creating a language context and then forcing I18N-dependent components to re-render when there is a change in the language. I could use guidance on two points though (no rush, I'm probably not going to start on this in earnest until mid next week.)

1. Right now I have LanguageContext as a separate component (using createContext/useContext). It didn't seem like the state management was complicated enough to justify using Redux. Do you think I should try to run it through there anyway? It would create more code, but potentially less overall complexity.

2. There are two ways I can force the components to re-render when language changes: a) setting the key of the component to be the language state, or b) manually passing the translated phrases to to the component. The former seems much more straightforward and would result in much fewer code changes, so that seems like the better option. It doesn't *seem* like there would be a significant performance difference between the two... is there one I'm not thinking of?
