### ISSUE TITLE
Redundant Tab Panel

### ISSUE THREAD

**Issue by mikhael28** [mikhael28/paretOS#43]
We are using essentially the same exact Tab Panel (the small functional component) in `ContextBuilder.js` and `Sprint.js` - can somebody please turn this into one exportable component, that is imported into both files?

**Comment by wesley3295** [comment]
What is the purpose of the Typography mui component on contextBuilder.js? It reduces the size of the tabs, by like 2px and honestly look better without the tag, and I have no context of what Sprint looks like without the Typography tag because there is no data coming into it. My opinion you could probably get rid of the tag. Let me know?

**Comment by mikhael28** [comment]
Great, let's continue discussing on the PR you submitted.

**Comment by mikhael28** [comment]
Closing, since this PR was merged in!
